### ISSUE TITLE
focusatwill workflow not working anymore

### ISSUE THREAD

**Issue by januz** [tangledhelix/focusatwill-in-google-chrome#2]
Thanks for your great workflow. I've been using it quite a bit, but recently it stopped working for me. When I execute the applescript, I get the error:

`execute tab 1 of window 1 javascript "$('.play').first().click()"`
`--> missing value`

Do you know what might be going on?

Also, in the Packal version there is no genre selection, right? Great that you added it!

**Comment by tangledhelix** [comment]
Version 1.3 fixes the Javascript problem, and also includes the Kora channels which were previously missing. I uploaded a new copy to Packal, so it should get this fix and also the genre support.

**Comment by januz** [comment]
Great, thanks a ton!!
