### ISSUE TITLE
install newest version

### ISSUE THREAD

**Issue by januz** [tangledhelix/focusatwill-in-google-chrome#3]
first of all -- thank you for this workflow, I use it everyday!

Since f@w updated their website, the old version of the workflow expectedly stopped working. I looked on packal and saw that the workflow wasn't updated for quite a while. Looking on your github it seems as if you have a relatively recent version (hopefully adapted to the new website?). I downloaded and installed the github version, but still the workflow doesn't work anymore for me.

Could you give me a hint what I might be doing wrong? Thanks!

**Comment by tangledhelix** [comment]
@januz I am not very good about updating Packal, sorry. I will try to remember to upload a new version today.

The version on Github is working for me. Are you using the latest version of Alfred? I know they updated the way workflows are built at some point, perhaps the workflow I posted does not work with older versions. I am using Alfred 3.4.1 currently.

**Comment by januz** [comment]
@tangledhelix Thanks for coming back to me!

I am using the newest version of Alfred and the newest version of the workflow from Github. Strangely, the workflow doesn't work still. Just to assure that there hasn't been a change in how it works:

- I have a tab in Chrome with the URL https://www.focusatwill.com/app/music
- I call the workflow with 'foc'

Could you please help me with how I can troubleshoot the issue? I tried to open the underlying script in ScriptEditor, but I couldn't execute it. 

Thanks!

**Comment by tangledhelix** [comment]
@januz I will look to make sure it should work the way you describe when I get a chance. But two questions:

1. What version of macOS are you using?
2. When you tried using Script Editor, did you change the language to JavaScript? The script is not Applescript, and Script Editor can run both (but you have to tell it which language to use, it does not auto-detect that).

**Comment by januz** [comment]
@tangledhelix 

1. I'm still on 10.11.6 
2. Yes, I changed it to JavaScript, but it gives the error `SyntaxError: Unexpected identifier 'tab'`

**Comment by tangledhelix** [comment]
@januz Perhaps 10.11 used an older Javascript runtime and was not able to use some of the ES2015 features that the script is using. I have ported it to use older Javascript features. Can you try this version in Script Editor and tell me if it works? If so then I will just publish a new release with this backward-compatible code.

```javascript
function run(argv) {

  var appUrl = "https://www.focusatwill.com/app/music";
  var browser = Application("Google Chrome");

  var tab, w, t;

  for (w = 0; w < browser.windows.length; w++) {
    for (t = 0; t < browser.windows[w].tabs.length; t++) {
      if (browser.windows[w].tabs[t].url().indexOf(appUrl) >= 0) {
        tab = browser.windows[w].tabs[t];
      }
    }
  }

  if (! tab) {
    var me = Application.currentApplication();
    me.includeStandardAdditions = true;
    me.displayNotification("Please open the site in Chrome.", {withTitle: "focus@will not found"});
    return;
  }

  if (["p", "pp", "play", "pause"].indexOf(argv[0]) >= 0) {
    tab.url = "javascript:if(window.faw.isPlaying){window.faw.stop()}else{window.faw.play()}";
  } else if (["n", "next", "skip"].indexOf(argv[0]) >= 0) {
    tab.url = "javascript:window.faw.skip()";
  } else if (["genre"].indexOf(argv[0] >= 0)) {
    var channelId = argv[0].split(' ')[1];
    tab.url = `javascript:window.faw.channel(${channelId})`;
  }
}
```

**Comment by tangledhelix** [comment]
@januz Actually in Script Editor it may do nothing at all because of the argv and such... but you can open the Alfred workflow and paste this Javascript in place of what is already there on your system.

**Comment by januz** [comment]
@tangledhelix The script works now, thank you so much!!

**Comment by tangledhelix** [comment]
I cut a new version, and I uploaded to both Github and Packal.

**Comment by januz** [comment]
Perfect, thanks you!
